# =============================================================================
# Instalación de Paquetes del Sistema - SellYourSaas
# Installation of system and application components
# =============================================================================
---
- name: "Instalación de paquetes del sistema SellYourSaas"
  hosts: "{{ target_hosts | default(target) }}"
  become: true
  gather_facts: yes

  tasks:
    # === DETECTAR VERSIÓN DE UBUNTU ===
    - name: "Detectar versión de Ubuntu"
      set_fact:
        ubuntu_version: "{{ ansible_distribution_version }}"
        ubuntu_major: "{{ ansible_distribution_version.split('.')[0] }}"

    - name: "Mostrar información del sistema"
      debug:
        msg:
          - "=== INFORMACIÓN DEL SISTEMA ==="
          - "Sistema: {{ ansible_distribution }} {{ ansible_distribution_version }}"
          - "Kernel: {{ ansible_kernel }}"
          - "Arquitectura: {{ ansible_architecture }}"
          - "Hostname: {{ ansible_hostname }}"

    # === ACTUALIZAR CACHE ===
    - name: "Actualizar cache de paquetes"
      apt:
        update_cache: yes
        cache_valid_time: 3600

    # === CONFIGURAR POSTFIX (PRECONFIGURACIÓN) ===
    - name: "Preconfigurar Postfix como Internet Site"
      debconf:
        name: postfix
        question: "{{ item.question }}"
        value: "{{ item.value }}"
        vtype: "{{ item.type }}"
      loop:
        - { question: "postfix/main_mailer_type", value: "Internet Site", type: "select" }
        - { question: "postfix/mailname", value: "{{ ansible_fqdn }}", type: "string" }
      register: postfix_config

    # === INSTALACIÓN POR VERSIÓN DE UBUNTU ===
    - name: "Instalar paquetes para Ubuntu 18.04-"
      apt:
        name:
          # Basic packages
          - ntp
          - git
          - gzip
          - zip
          - zstd
          - memcached
          - ncdu
          - duc
          - iotop
          - acl
          - ufw
          - sudo
          # Database
          - mariadb-server
          - mariadb-client
          # Web server
          - apache2
          - apache2-bin
          - lynx
          # PHP packages
          - php
          - php-cli
          - libapache2-mod-php
          - php-fpm
          - php-gd
          - php-imap
          - php-json
          - php-ldap
          - php-mysqlnd
          - php-curl
          - php-memcached
          - php-imagick
          - php-geoip
          - php-mcrypt
          - php-intl
          - php-xml
          - php-zip
          - php-bz2
          - php-ssh2
          - php-mbstring
          - php-soap
          - php-tidy
          - php-readline
          - php-xmlrpc
          - php-pear
          # Security and system
          - watchdog
          - cpulimit
          - libapache2-mpm-itk
          - libapache2-mod-apparmor
          - apparmor
          - apparmor-profiles
          - apparmor-utils
          - rkhunter
          - chkrootkit
          - bind9
          - spamc
          - spamassassin
          - clamdscan
          - clamav-daemon
          - fail2ban
          - soffice
          - libreoffice-common
          - libreoffice-writer
          - mailutils
          - postfix
        state: present
      when: ubuntu_major | int < 20
      register: packages_1804

    - name: "Instalar paquetes para Ubuntu 20.04+"
      apt:
        name:
          # Basic packages
          - systemd-timesyncd
          - git
          - gzip
          - zip
          - zstd
          - memcached
          - ncdu
          - duc
          - iotop
          - acl
          - ufw
          - sudo
          # Database
          - mariadb-server
          - mariadb-client
          # Web server
          - apache2
          - apache2-bin
          - lynx
          # PHP packages
          - php
          - php-cli
          - libapache2-mod-php
          - php-fpm
          - php-gd
          - php-imap
          - php-json
          - php-ldap
          - php-mysql
          - php-curl
          - php-memcached
          - php-imagick
          - php-geoip
          - php-intl
          - php-xml
          - php-zip
          - php-bz2
          - php-ssh2
          - php-mbstring
          - php-dev
          - php-soap
          - php-tidy
          - libmcrypt-dev
          - php-readline
          - php-xmlrpc
          - php-pear
          - ghostscript
          # Security and system
          - watchdog
          - cpulimit
          - libapache2-mpm-itk
          - libapache2-mod-apparmor
          - apparmor
          - apparmor-profiles
          - apparmor-utils
          - rkhunter
          - chkrootkit
          - bind9
          - spamc
          - spamassassin
          - clamav
          - clamav-daemon
          - fail2ban
          - libreoffice-common
          - libreoffice-writer
          - mailutils
          - postfix
        state: present
      when: ubuntu_major | int >= 20 and ubuntu_major | int < 22
      register: packages_2004

    - name: "Instalar paquetes para Ubuntu 22.04+ y 24.04+"
      apt:
        name:
          # Basic packages
          - systemd-timesyncd
          - git
          - gzip
          - zip
          - zstd
          - memcached
          - ncdu
          - duc
          - iotop
          - acl
          - ufw
          - sudo
          # Database
          - mariadb-server
          - mariadb-client
          # Web server
          - apache2
          - apache2-bin
          - lynx
          # PHP packages
          - php
          - php-cli
          - libapache2-mod-php
          - php-fpm
          - php-gd
          - php-imap
          - php-json
          - php-ldap
          - php-mysql
          - php-curl
          - php-memcached
          - php-imagick
          - php-intl
          - php-xml
          - php-zip
          - php-bz2
          - php-ssh2
          - php-mbstring
          - php-dev
          - php-soap
          - php-tidy
          - libmcrypt-dev
          - php-readline
          - php-xmlrpc
          - php-pear
          - ghostscript
          # Security and system
          - watchdog
          - cpulimit
          - libapache2-mpm-itk
          - libapache2-mod-apparmor
          - apparmor
          - apparmor-profiles
          - apparmor-utils
          - rkhunter
          - chkrootkit
          - bind9
          - spamc
          - spamassassin
          - clamav
          - clamav-daemon
          - fail2ban
          - libreoffice-common
          - libreoffice-writer
          - mailutils
          - postfix
        state: present
      when: ubuntu_major | int >= 22
      register: packages_2204

    # === VERIFICACIONES POST-INSTALACIÓN ===
    - name: "Verificar versión de PHP instalada"
      command: php --version
      register: php_version_output
      changed_when: false

    - name: "Verificar estado de servicios críticos"
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - apache2
        - mariadb
        - postfix
        - fail2ban
        - clamav-daemon
        - spamassassin
      register: services_check

    - name: "Verificar paquetes instalados"
      command: dpkg -l {{ item }}
      register: package_verification
      failed_when: false
      changed_when: false
      loop:
        - apache2
        - php
        - mariadb-server
        - postfix
        - fail2ban
        - clamav-daemon
        - spamassassin
        - bind9
        - apparmor

    # === CONFIGURACIONES ADICIONALES ===
    - name: "Configurar timezone"
      timezone:
        name: "{{ system_timezone | default('UTC') }}"

    - name: "Desactivar actualizaciones automáticas"
      package:
        name: unattended-upgrades
        state: absent
      ignore_errors: yes

    # === MOSTRAR RESUMEN COMPLETO ===
    - name: "Mostrar resumen de instalación"
      debug:
        msg:
          - "=== INSTALACIÓN DE PAQUETES COMPLETADA ==="
          - "Sistema: {{ ansible_distribution }} {{ ansible_distribution_version }}"
          - "Versión de paquetes instalada: {{ 'Ubuntu 18.04-' if ubuntu_major | int < 20 else ('Ubuntu 20.04+' if ubuntu_major | int < 22 else 'Ubuntu 22.04+/24.04+') }}"
          - "Instalación: {{ 'exitosa' if (packages_1804.changed or packages_2004.changed or packages_2204.changed) else 'sin cambios' }}"
          - "Comandos ejecutados equivalentes:"
          - "  • sudo apt update"
          - "  • sudo apt install -y {{ 'ntp' if ubuntu_major | int < 20 else 'systemd-timesyncd' }} git gzip zip zstd memcached ncdu duc iotop acl ufw sudo"
          - "  • sudo apt install -y mariadb-server mariadb-client"
          - "  • sudo apt install -y apache2 apache2-bin lynx"
          - "  • sudo apt install -y php php-cli libapache2-mod-php php-fpm php-gd php-imap php-json php-ldap {{ 'php-mysqlnd' if ubuntu_major | int < 20 else 'php-mysql' }} php-curl php-memcached php-imagick {{ 'php-geoip' if ubuntu_major | int < 22 else '' }} {{ 'php-mcrypt' if ubuntu_major | int < 20 else 'libmcrypt-dev' }} php-intl php-xml php-zip php-bz2 php-ssh2 php-mbstring php-soap php-tidy"
          - "  • sudo apt install -y php-readline php-xmlrpc php-pear {{ 'ghostscript' if ubuntu_major | int >= 20 else '' }}"
          - "  • sudo apt install -y watchdog cpulimit libapache2-mpm-itk libapache2-mod-apparmor apparmor apparmor-profiles apparmor-utils rkhunter chkrootkit"
          - "  • sudo apt install -y bind9"
          - "  • sudo apt install -y spamc spamassassin {{ 'clamdscan' if ubuntu_major | int < 20 else 'clamav' }} clamav-daemon"
          - "  • sudo apt install -y fail2ban"
          - "  • sudo apt install -y {{ 'soffice' if ubuntu_major | int < 20 else '' }} libreoffice-common libreoffice-writer"
          - "  • sudo apt install -y mailutils postfix"
          - "Versión PHP: {{ php_version_output.stdout_lines[0] if php_version_output.stdout_lines else 'Error obteniendo versión' }}"
          - "Servicios habilitados: apache2, mariadb, postfix, fail2ban, clamav-daemon, spamassassin"
          - "Configuración Postfix: Internet Site ({{ ansible_fqdn }})"
          - "Timezone: {{ system_timezone | default('UTC') }}"
          - "Actualizaciones automáticas: desactivadas"
