# =============================================================================
# Instalación y Configuración Dolibarr en Master
# =============================================================================
---
- name: "Instalación Dolibarr Master"
  hosts: '{{ target }}'
  become: true
  gather_facts: yes

  tasks:
    - name: "Crear directorio wwwroot si no existe"
      file:
        path: "/home/{{ system_users.admin }}/wwwroot"
        state: directory
        owner: "{{ system_users.admin }}"
        group: "{{ system_users.admin }}"
        mode: '0755'

    - name: "Verificar si Dolibarr ya está clonado"
      stat:
        path: "/home/{{ system_users.admin }}/wwwroot/dolibarr"
      register: dolibarr_exists

    - name: "Limpiar directorio Dolibarr si existe (para reclonado)"
      file:
        path: "/home/{{ system_users.admin }}/wwwroot/dolibarr"
        state: absent
      when: dolibarr_exists.stat.exists and (force_reclone | default(false))

    - name: "Configurando Git safe directory para Dolibarr"
      ansible.builtin.command:
        cmd: git config --global --add safe.directory /home/{{ system_users.admin }}/wwwroot/dolibarr
      become_user: "{{ system_users.admin }}"

    - name: "Clonando Dolibarr desde {{ dolibarr.repo }} en la rama {{ dolibarr.branch }}"
      ansible.builtin.git:
        repo: "{{ dolibarr.repo }}"
        dest: "/home/{{ system_users.admin }}/wwwroot/dolibarr"
        version: "{{ dolibarr.branch }}"
        force: yes
        update: yes
      become_user: "{{ system_users.admin }}"
      when: not dolibarr_exists.stat.exists or (force_reclone | default(false))

    - name: "Actualizar Dolibarr si ya existe"
      ansible.builtin.git:
        repo: "{{ dolibarr.repo }}"
        dest: "/home/{{ system_users.admin }}/wwwroot/dolibarr"
        version: "{{ dolibarr.branch }}"
        update: yes
      become_user: "{{ system_users.admin }}"
      when: dolibarr_exists.stat.exists and not (force_reclone | default(false))

## Clonando SellYourSaas
    - name: "Verificar si SellYourSaas ya está clonado"
      stat:
        path: "/home/{{ system_users.admin }}/wwwroot/sellyoursaas"
      register: sellyoursaas_exists

    - name: "Limpiar directorio SellYourSaas si existe (para reclonado)"
      file:
        path: "/home/{{ system_users.admin }}/wwwroot/sellyoursaas"
        state: absent
      when: sellyoursaas_exists.stat.exists and (force_reclone | default(false))

    - name: "Configurando Git safe directory para SellYourSaas"
      ansible.builtin.command:
        cmd: git config --global --add safe.directory /home/{{ system_users.admin }}/wwwroot/sellyoursaas
      become_user: "{{ system_users.admin }}"

    - name: "Clonando SellYourSaas desde {{ sellyoursaas.repo }} "
      ansible.builtin.git:
        repo: "{{ sellyoursaas.repo }}"
        dest: "/home/{{ system_users.admin }}/wwwroot/sellyoursaas"
        force: yes
        update: yes
      become_user: "{{ system_users.admin }}"
      when: not sellyoursaas_exists.stat.exists or (force_reclone | default(false))

    - name: "Actualizar SellYourSaas si ya existe"
      ansible.builtin.git:
        repo: "{{ sellyoursaas.repo }}"
        dest: "/home/{{ system_users.admin }}/wwwroot/sellyoursaas"
        update: yes
      become_user: "{{ system_users.admin }}"
      when: sellyoursaas_exists.stat.exists and not (force_reclone | default(false))

    - name: "Configurar permisos para Dolibarr"
      file:
        path: "/home/{{ system_users.admin }}/wwwroot/dolibarr"
        owner: "{{ system_users.admin }}"
        group: www-data
        mode: '0755'
        recurse: no

    - name: "Configurar permisos para SellYourSaas"
      file:
        path: "/home/{{ system_users.admin }}/wwwroot/sellyoursaas"
        owner: "{{ system_users.admin }}"
        group: www-data
        mode: '0755'
        recurse: no

    - name: "Mostrar directorios clonados"
      debug:
        msg: |
          Repositorios clonados en:
          - Dolibarr: /home/{{ system_users.admin }}/wwwroot/dolibarr
          - SellYourSaas: /home/{{ system_users.admin }}/wwwroot/sellyoursaas