# =============================================================================
# Configuración de política de contraseñas
# =============================================================================
---
- name: "Configuración de política de contraseñas"
  hosts: "{{ target_hosts | default('master,deploy') }}"
  become: true
  gather_facts: yes

  tasks:
    - name: "Configurar longitud mínima de contraseña en PAM"
      lineinfile:
        path: /etc/pam.d/common-password
        regexp: '^password\s+\[success=1 default=ignore\]\s+pam_unix\.so'
        line: 'password        [success=1 default=ignore]      pam_unix.so obscure sha512 minlength=16'
        backup: yes

    - name: "Verificar configuración de PAM"
      command: grep minlength /etc/pam.d/common-password
      register: pam_check
      changed_when: false

    - name: "Mostrar configuración de contraseñas"
      debug:
        msg: "{{ pam_check.stdout_lines }}"
