# =============================================================================
# Configuración script monitoreo basic.sh
# =============================================================================
---
- name: "Configuración script basic.sh de monitoreo"
  hosts: "{{ target_hosts | default('all') }}"
  become: true
  gather_facts: yes

  tasks:
    - name: "Crear directorio para scripts de monitoreo"
      file:
        path: /home/admin/monitor
        state: directory
        owner: admin
        group: admin
        mode: '0755'

    - name: "Crear script de monitoreo basic.sh"
      copy:
        content: |
          #!/bin/bash
          # Script de monitoreo básico para SellYourSaas
          # Generado por Ansible

          # Colores para output
          RED='\033[0;31m'
          GREEN='\033[0;32m'
          YELLOW='\033[1;33m'
          NC='\033[0m' # No Color

          echo -e "${GREEN}===========================================${NC}"
          echo -e "${GREEN} MONITOR BÁSICO SELLYOURSAAS - $(date)${NC}"
          echo -e "${GREEN}===========================================${NC}"

          # 1. Estado del sistema
          echo -e "\n${YELLOW}[SISTEMA]${NC}"
          echo "Uptime: $(uptime)"
          echo "Load Average: $(cat /proc/loadavg | cut -d' ' -f1-3)"
          echo "Memoria libre: $(free -h | grep Mem | awk '{print $7}')"
          echo "Disco libre /: $(df -h / | awk 'NR==2{print $4}')"

          # 2. Servicios críticos
          echo -e "\n${YELLOW}[SERVICIOS]${NC}"
          services=("apache2" "mysql" "nfs-kernel-server" "fail2ban" "ssh")
          for service in "${services[@]}"; do
              if systemctl is-active --quiet $service; then
                  echo -e "$service: ${GREEN}ACTIVO${NC}"
              else
                  echo -e "$service: ${RED}INACTIVO${NC}"
              fi
          done

          # 3. Conexiones MySQL
          echo -e "\n${YELLOW}[MYSQL]${NC}"
          mysql_connections=$(mysql -e "SHOW STATUS LIKE 'Threads_connected';" | tail -1 | awk '{print $2}')
          echo "Conexiones activas: $mysql_connections"

          # 4. Procesos Apache
          echo -e "\n${YELLOW}[APACHE]${NC}"
          apache_procs=$(ps aux | grep apache2 | grep -v grep | wc -l)
          echo "Procesos Apache: $apache_procs"

          # 5. Log de errores recientes
          echo -e "\n${YELLOW}[ERRORES RECIENTES]${NC}"
          echo "Últimos 5 errores Apache:"
          tail -5 /var/log/apache2/error.log 2>/dev/null || echo "Sin errores"

          # 6. Espacio en directorios importantes
          echo -e "\n${YELLOW}[ESPACIO EN DISCO]${NC}"
          echo "/home: $(du -sh /home 2>/dev/null | cut -f1)"
          echo "/var/log: $(du -sh /var/log 2>/dev/null | cut -f1)"
          echo "/tmp: $(du -sh /tmp 2>/dev/null | cut -f1)"

          echo -e "\n${GREEN}=========================================${NC}"
        dest: /home/admin/monitor/basic.sh
        owner: admin
        group: admin
        mode: '0755'

    - name: "Crear cron job para monitoreo cada 15 minutos"
      cron:
        name: "Monitor básico SellYourSaas"
        minute: "*/15"
        job: "/home/admin/monitor/basic.sh > /home/admin/monitor/basic.log 2>&1"
        user: admin

    - name: "Crear enlace simbólico en PATH"
      file:
        src: /home/admin/monitor/basic.sh
        dest: /usr/local/bin/basic
        state: link

    - name: "Información del script creado"
      debug:
        msg:
          - "Script basic.sh creado en /home/admin/monitor/"
          - "Accesible globalmente como 'basic'"
          - "Cron configurado cada 15 minutos"
          - "Log disponible en /home/admin/monitor/basic.log"
