# =============================================================================
# Configuración usuario personal sysadmin (jpyrsaadmin)
# =============================================================================
---
- name: "Configuración usuario personal sysadmin"
  hosts: "{{ target_hosts | default('master,deploy') }}"
  become: true
  gather_facts: yes

  vars:
    sysadmin_username: "{{ personal_sysadmin_user | default('jpyrsaadmin') }}"

  tasks:
    - name: "Crear usuario personal sysadmin"
      user:
        name: "{{ sysadmin_username }}"
        shell: /usr/bin/bash
        create_home: yes
        state: present
      register: user_created

    - name: "Crear archivo sudoers para usuario personal"
      copy:
        content: |
          {{ sysadmin_username }} ALL=(ALL) ALL
          # Permite cambiar a admin o osu* sin password
          {{ sysadmin_username }} ALL=(ALL) /usr/bin/su - admin
          {{ sysadmin_username }} ALL=(ALL) /usr/bin/su - osu*
        dest: "/etc/sudoers.d/{{ sysadmin_username }}"
        mode: '0440'
        owner: root
        group: root
        validate: 'visudo -cf %s'

    - name: "Aplicar permisos correctos al archivo sudoers"
      file:
        path: "/etc/sudoers.d/{{ sysadmin_username }}"
        mode: '0440'
        owner: root
        group: root
      register: sudoers_perms

    - name: "Generar claves SSH para usuario personal"
      user:
        name: "{{ sysadmin_username }}"
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
      when: user_created.changed

    - name: "Mostrar clave pública del usuario personal"
      command: "cat /home/{{ sysadmin_username }}/.ssh/id_rsa.pub"
      register: personal_pubkey
      changed_when: false

    - name: "Información del usuario personal creado"
      debug:
        msg:
          - "Usuario {{ sysadmin_username }} creado exitosamente"
          - "Clave pública: {{ personal_pubkey.stdout }}"
          - "Para copiar la clave SSH a una máquina remota, use:"
          - "ssh-copy-id {{ sysadmin_username }}@x.y.z.a"
          - "Para probar la conexión, use:"
          - "ssh -v {{ sysadmin_username }}@x.y.z.a"
          - "sudo -s"
