# =============================================================================
# CONFIGURACIÓN DE HOSTNAME COMO TASKS
# =============================================================================
# Este archivo contiene las tareas para configurar hostname
# Puede ser incluido en otros playbooks usando include_tasks
# =============================================================================
---
- name: Mostrar información del hostname
  debug:
    msg: |
      Configurando hostname: {{ hostname_main | default(master_server.hostname) }}
      En servidor: {{ inventory_hostname }}
      IP: {{ ansible_host | default('N/A') }}
      Tipo: {{ server_type | default('N/A') }}

- name: Configurar hostname del servidor
  hostname:
    name: "{{ hostname_main | default(master_server.hostname) }}"
  become: true
  
- name: Verificar hostname configurado
  command: hostname
  register: current_hostname
  become: true
  
- name: Mostrar hostname actual
  debug:
    msg: "Hostname configurado: {{ current_hostname.stdout }}"

- name: Actualizar /etc/hosts con el nuevo hostname
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1 {{ hostname_main | default(master_server.hostname) }}"
    backup: yes
  become: true
