---
- name: "Setup of PHP"
  hosts: '{{ target }}'
  gather_facts: no
  tasks:
    - name: Secure the directory of PHP sessions /dev/shm
      ansible.builtin.file:
        path: /dev/shm
        mode: '0733'
        state: directory
        recurse: true
    - name: Set sticky bit for PHP session directories /var/lib/php/sessions
      ansible.builtin.file:
        path: /var/lib/php/sessions
        mode: '1733'
        state: directory
        recurse: true
    - name: "Define size of upload and session options"
      blockinfile:
        path: /etc/php/sellyoursaas.ini
        create: yes
        block: |
          link:repository_root/etc/php/sellyoursaas.ini[role=include]
        marker: "# {mark} ANSIBLE MANAGED Setup PHP"
    - name: Define size of upload and session options
      file:
        src: /etc/php/sellyoursaas.ini
        dest: '{{ item }}'
        state: link
        loop:
          - /etc/php/8.3/apache2/conf.d
          - /etc/php/8.3/cli/conf.d
          - /etc/php/8.3/fpm/conf.d
    - name: "Add a wrapper PHP for the mail() function [Master]"
      blockinfile:
        path: /etc/logrotate.d/logrotate_admin_log
        create: yes
        block: |
          
        marker: "# {mark} ANSIBLE MANAGED ADMIN LOGROTATE"
        loop:
          - /home/admin/wwwroot/dolibarr_documents/sellyoursaas/spam/blacklistmail;
          - /home/admin/wwwroot/dolibarr_documents/sellyoursaas/spam/blacklistip;
          - /home/admin/wwwroot/dolibarr_documents/sellyoursaas/spam/blacklistfrom;
          - /home/admin/wwwroot/dolibarr_documents/sellyoursaas/spam/blacklistcontent;