# =============================================================================
# Configuración de claves SSH SellYourSaas - Shared (Master y Deploy)
# Deploy the public key of master admin on deployment admin account
# /home/admin/.ssh/id_rsa_sellyoursaas
# =============================================================================
---
- name: "Configuración claves SSH SellYourSaas"
  hosts: "{{ target_hosts | default('all') }}"
  become: true
  gather_facts: yes

  tasks:
    # === DETECTAR TIPO DE SERVIDOR ===
    - name: "Detectar tipo de servidor"
      set_fact:
        server_type: "{{ 'master' if inventory_hostname in groups['master'] else 'deploy' }}"

    # === CREAR DIRECTORIO SSH ===
    - name: "Crear directorio .ssh para usuario admin"
      file:
        path: "/home/admin/.ssh"
        state: directory
        owner: admin
        group: admin
        mode: '0700'

    # =====================================================================
    # CONFIGURACIÓN ESPECÍFICA PARA SERVIDOR MASTER
    # =====================================================================
    - name: "Configuración SSH para servidor MASTER"
      block:
        - name: "Generar claves SSH SellYourSaas en Master"
          openssh_keypair:
            path: "/home/admin/.ssh/id_rsa_sellyoursaas"
            type: rsa
            size: 4096
            owner: admin
            group: admin
            mode: '0600'
            comment: "admin@sellyoursaas-{{ inventory_hostname }}"
          register: ssh_key_generated
          
        - name: "Recuperar contenido de clave privada"
          slurp:
            src: "/home/admin/.ssh/id_rsa_sellyoursaas"
          register: private_key_master
          
        - name: "Recuperar contenido de clave pública"
          slurp:
            src: "/home/admin/.ssh/id_rsa_sellyoursaas.pub"
          register: public_key_master
          
        - name: "Guardar claves en variables de hecho"
          set_fact:
            master_private_key: "{{ private_key_master.content | b64decode }}"
            master_public_key: "{{ public_key_master.content | b64decode }}"
      when: server_type == 'master'

    # =====================================================================
    # CONFIGURACIÓN ESPECÍFICA PARA SERVIDOR DEPLOY
    # =====================================================================
    - name: "Configuración SSH para servidor DEPLOY"
      block:
        # Esta tarea se ejecuta en el servidor de deploy
        # Pero necesita datos del servidor master, por lo que hacemos una conexión
        # delegada al master para obtener las claves
        - name: "Obtener claves SSH del servidor Master"
          block:
            - name: "Recuperar clave privada del Master"
              slurp:
                src: "/home/admin/.ssh/id_rsa_sellyoursaas"
              register: private_key_master
              delegate_to: "{{ groups['master'][0] }}"
              become: yes
              
            - name: "Recuperar clave pública del Master"
              slurp:
                src: "/home/admin/.ssh/id_rsa_sellyoursaas.pub"
              register: public_key_master
              delegate_to: "{{ groups['master'][0] }}"
              become: yes
              
            - name: "Guardar claves en variables de hecho"
              set_fact:
                master_private_key: "{{ private_key_master.content | b64decode }}"
                master_public_key: "{{ public_key_master.content | b64decode }}"
          rescue:
            - name: "Generar mensaje de error si no se pueden obtener las claves del Master"
              debug:
                msg: "ERROR: No se pudieron obtener las claves SSH del servidor Master. Asegúrate de que el servidor Master esté configurado y accesible."
              failed_when: true
          
        # Ahora creamos los archivos en el servidor deploy con las claves obtenidas
        - name: "Crear clave privada en servidor Deploy"
          copy:
            content: "{{ master_private_key }}"
            dest: "/home/admin/.ssh/id_rsa_sellyoursaas"
            owner: admin
            group: admin
            mode: '0600'
            
        - name: "Crear clave pública en servidor Deploy"
          copy:
            content: "{{ master_public_key }}"
            dest: "/home/admin/.ssh/id_rsa_sellyoursaas.pub"
            owner: admin
            group: admin
            mode: '0644'
      when: server_type == 'deploy'

    # === ESTABLECER PERMISOS CORRECTOS ===
    - name: "Establecer permisos en claves SSH"
      file:
        path: "{{ item.path }}"
        owner: admin
        group: admin
        mode: "{{ item.mode }}"
      loop:
        - { path: "/home/admin/.ssh/id_rsa_sellyoursaas", mode: "0600" }
        - { path: "/home/admin/.ssh/id_rsa_sellyoursaas.pub", mode: "0644" }

    - name: "Aplicar permisos específicos con chmod"
      shell: |
        chmod u+rw /home/admin/.ssh/id_rsa_sellyoursaas*
        chmod go-rw /home/admin/.ssh/id_rsa_sellyoursaas*
        chmod a+r /home/admin/.ssh/id_rsa_sellyoursaas.pub

    # === CREAR/ACTUALIZAR ARCHIVO SSH CONFIG ===
    - name: "Crear o actualizar archivo SSH config"
      template:
        src: ssh_config.j2
        dest: "/home/admin/.ssh/config"
        owner: admin
        group: admin
        mode: '0600'
        backup: yes

    - name: "Establecer permisos correctos en SSH config"
      file:
        path: "/home/admin/.ssh/config"
        owner: admin
        group: admin
        mode: '0600'

    - name: "Aplicar permisos con chmod y chown"
      shell: |
        chmod 600 /home/admin/.ssh/config
        chown admin:admin /home/admin/.ssh/config

    # === VERIFICACIONES ===
    - name: "Verificar que las claves existen"
      stat:
        path: "{{ item }}"
      register: ssh_keys_check
      loop:
        - "/home/admin/.ssh/id_rsa_sellyoursaas"
        - "/home/admin/.ssh/id_rsa_sellyoursaas.pub"
        - "/home/admin/.ssh/config"

    - name: "Verificar permisos de las claves"
      command: ls -la /home/admin/.ssh/id_rsa_sellyoursaas*
      register: ssh_perms_check
      changed_when: false

    - name: "Verificar contenido del archivo SSH config"
      command: cat /home/admin/.ssh/config
      register: ssh_config_content
      changed_when: false

    # === MOSTRAR RESUMEN ===
    - name: "Mostrar resumen de configuración SSH"
      debug:
        msg:
          - "=== CONFIGURACIÓN SSH SELLYOURSAAS COMPLETADA ==="
          - "Servidor: {{ inventory_hostname }}"
          - "Tipo: {{ server_type }}"
          - "Archivos creados:"
          - "  • /home/admin/.ssh/id_rsa_sellyoursaas (0600)"
          - "  • /home/admin/.ssh/id_rsa_sellyoursaas.pub (0644)"
          - "  • /home/admin/.ssh/config (0600)"
          - "Comandos ejecutados:"
          - "  • chmod u+rw /home/admin/.ssh/id_rsa_sellyoursaas*"
          - "  • chmod go-rw /home/admin/.ssh/id_rsa_sellyoursaas*"
          - "  • chmod a+r /home/admin/.ssh/id_rsa_sellyoursaas.pub"
          - "  • chmod 600 /home/admin/.ssh/config"
          - "  • chown admin:admin /home/admin/.ssh/config"
          - "{{ '=' * 50 }}"
          - "PROCESO AUTOMATIZADO:"
          - "{{ '=' * 50 }}"
          - "{% if server_type == 'master' %}"
          - "✅ Se han generado las claves SSH en el servidor Master"
          - "{% elif server_type == 'deploy' %}"
          - "✅ Se han copiado las claves SSH del servidor Master al servidor Deploy"
          - "{% endif %}"
          - "✅ Se ha configurado el archivo SSH config con:"
          - "   • Host {{ deployment_server_ip | default('ip.server.deployment') }}"
          - "   • Host github.com"
          - "   • IdentityFile /home/admin/.ssh/id_rsa_sellyoursaas"
          - "Permisos aplicados:"
          - "{{ ssh_perms_check.stdout_lines | default(['Error verificando permisos']) }}"
