- name: Unix personal sysadmin account
  hosts: '{{ target }}'
  become: yes
  become_user: root
  tasks:
    - name: 'Agregando al administrador del sistema {{ system_users.UnixPersonalSysadmin }} con sus respectivas claves'
      ansible.builtin.user:
        name: '{{ system_users.UnixPersonalSysadmin }}'
        password: "{{ system_users.UnixPersonalSysadmin_password | password_hash('sha512') }}"
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa

    - name: "Creando el archivo /etc/sudoers.d/{{ system_users.UnixPersonalSysadmin }}"
      copy:
        dest: "/etc/sudoers.d/{{ system_users.UnixPersonalSysadmin }}"
        content: |
          {{ system_users.UnixPersonalSysadmin }} ALL=(ALL) ALL
          {{ system_users.UnixPersonalSysadmin }} ALL=(ALL) /usr/bin/su - admin
          {{ system_users.UnixPersonalSysadmin }} ALL=(ALL) /usr/bin/su - osu*
        owner: root
        group: root
        mode: '0440'

    - name: "Asegurar que el directorio .ssh existe"
      file:
        path: "/home/{{ system_users.UnixPersonalSysadmin }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ system_users.UnixPersonalSysadmin }}"
        group: "{{ system_users.UnixPersonalSysadmin }}"

    - name: "Agregar clave pública a authorized_keys"
      ansible.posix.authorized_key:
        user: "{{ system_users.UnixPersonalSysadmin }}"
        state: present
        key: "{{ ssh_keys.admin_public }}"
        path: "/home/{{ system_users.UnixPersonalSysadmin }}/.ssh/authorized_keys"