# =============================================================================
# Creation of working directories
# =============================================================================
---
- name: 'Crear directorios de trabajo'
  hosts: master
  become: true
  gather_facts: yes

  tasks:
    - name: 'Crear directorios de trabajo principales'
      file:
        path: '{{ item }}'
        state: directory
        owner: '{{ system_users.admin }}'
        group: root
        mode: '0755'
        recurse: yes
      loop:
        - '{{ directories.diskhome }}/backup' # ok
        - '{{ directories.jail }}' # ok
        - '{{ directories.diskhome }}/home' # ok
        - '{{ directories.diskbackup }}/archives-test'
        - '{{ directories.diskbackup }}archives-paid'
        - '/home/admin/wwwroot/dolibarr_documents/sellyoursaas/spam'
    
    - name: 'Crear enlaces simbólicos de directorios'
      file:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
        state: link
        owner: '{{ system_users.admin }}'
        group: admin
      loop:
        - { src: '{{ directories.diskhome }}/backup', dest: '{{ directories.diskbackup }}/backup' }


    - name: 'Crear enlace simbólico para backup'
      file:
        src: '{{ directories.diskhome }}/backup'
        dest: '{{ directories.diskbackup }}/backup'
        state: link
        force: yes
