# =============================================================================
# Eliminación de archivos de información al login (motd) en servidores de deployment
# =============================================================================
---
- name: 'Eliminación de archivos de información al login (motd)'
  hosts: '{{ target }}'
  become: true
  gather_facts: yes

  tasks:
    - name: 'Eliminar archivos de información de motd'
      file:
        path: '{{ item }}'
        state: absent
      loop:
        - /etc/update-motd.d/00-header
        - /etc/update-motd.d/20-runabove
        - /etc/update-motd.d/50-landscape-sysinfo
        - /etc/update-motd.d/50-motd-news
        - /etc/update-motd.d/92-unattended-upgrades
        - /etc/update-motd.d/99-update-available
        - /etc/update-motd.d/91-update-available
        - /etc/update-motd.d/90-update-available
        - /etc/update-motd.d/98-update-available
      failed_when: false
