# =============================================================================
# Eliminación de archivos de información en login
# =============================================================================
---
- name: "Eliminar archivos de información al login"
  hosts: deploy
  become: true
  gather_facts: yes

  tasks:
    - name: "Eliminar archivos de información MOTD"
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/update-motd.d/00-header
        - /etc/update-motd.d/20-runabove
        - /etc/update-motd.d/50-landscape-sysinfo
        - /etc/update-motd.d/50-motd-news
        - /etc/update-motd.d/90-updates-available
        - /etc/update-motd.d/91-release-upgrade
        - /etc/update-motd.d/92-unattended-upgrades
        - /etc/update-motd.d/95-hwe-eol
      ignore_errors: yes

    - name: "Crear MOTD personalizado mínimo"
      copy:
        content: |
          #!/bin/sh
          echo "SellYourSaas Deployment Server"
          echo "Unauthorized access is prohibited"
        dest: /etc/update-motd.d/00-sellyoursaas
        mode: '0755'
        owner: root
        group: root
