# =============================================================================
# Configuración NFS Cliente en Deploy - SellYourSaas
# Installing the nfs share - On the Deployment Servers
# =============================================================================
---
- name: "Configuración NFS Cliente para SellYourSaas"
  hosts: deploy
  become: true
  gather_facts: yes

  tasks:
    # === CREAR DIRECTORIO DE DOCUMENTOS SELLYOURSAAS ===
    - name: "Crear directorio de documentos de Dolibarr/SellYourSaas"
      file:
        path: "/home/admin/wwwroot/dolibarr_documents/sellyoursaas"
        state: directory
        owner: admin
        group: admin
        mode: '0755'
        recurse: yes

    # === INSTALAR NFS CLIENT ===
    - name: "Instalar nfs-common"
      package:
        name: nfs-common
        state: present
        update_cache: yes

    # === PROBAR MONTAJE MANUAL ===
    - name: "Probar montaje manual NFS"
      mount:
        path: "/home/admin/wwwroot/dolibarr_documents/sellyoursaas"
        src: "{{ master_server_ip | default('i.p.server.master') }}:/home/admin/wwwroot/dolibarr_documents/sellyoursaas"
        fstype: nfs
        opts: defaults
        state: mounted
      register: nfs_mount_test

    - name: "Verificar montaje NFS"
      command: df -h /home/admin/wwwroot/dolibarr_documents/sellyoursaas
      register: nfs_mount_check
      when: nfs_mount_test is succeeded

    - name: "Desmontar para configurar fstab"
      mount:
        path: "/home/admin/wwwroot/dolibarr_documents/sellyoursaas"
        state: unmounted
      when: nfs_mount_test is succeeded

    # === CONFIGURAR /etc/fstab ===
    - name: "Verificar si la entrada NFS ya existe en /etc/fstab"
      lineinfile:
        path: /etc/fstab
        regexp: '.*sellyoursaas.*nfs.*'
        state: absent
      check_mode: yes
      register: fstab_check

    - name: "Agregar entrada NFS a /etc/fstab"
      lineinfile:
        path: /etc/fstab
        line: "{{ master_server_ip | default('i.p.server.master') }}:/home/admin/wwwroot/dolibarr_documents/sellyoursaas /home/admin/wwwroot/dolibarr_documents/sellyoursaas  nfs  defaults 0 0"
        backup: yes
        insertafter: EOF
      when: fstab_check is not changed

    # === PROBAR MONTAJE AUTOMÁTICO ===
    - name: "Probar montaje automático con mount -a"
      command: mount -a
      register: mount_auto_result

    - name: "Verificar que el montaje automático funciona"
      mount:
        path: "/home/admin/wwwroot/dolibarr_documents/sellyoursaas"
        src: "{{ master_server_ip | default('i.p.server.master') }}:/home/admin/wwwroot/dolibarr_documents/sellyoursaas"
        fstype: nfs
        opts: defaults
        state: mounted

    # === VERIFICACIONES FINALES ===
    - name: "Verificar montaje NFS activo"
      command: mount | grep sellyoursaas
      register: nfs_active_mount
      changed_when: false

    - name: "Verificar conectividad con servidor master"
      command: "netstat -n | grep {{ master_server_ip | default('i.p.server.master') }}"
      register: nfs_connectivity
      changed_when: false
      ignore_errors: yes

    - name: "Verificar acceso de lectura al montaje NFS"
      command: ls -la /home/admin/wwwroot/dolibarr_documents/sellyoursaas
      register: nfs_read_test
      changed_when: false

    - name: "Verificar estado del servicio NFS"
      command: systemctl status nfs-common
      register: nfs_client_status
      changed_when: false

    # === MOSTRAR RESUMEN ===
    - name: "Mostrar resumen de configuración NFS Cliente"
      debug:
        msg:
          - "=== CONFIGURACIÓN NFS CLIENTE COMPLETADA ==="
          - "Servidor Master: {{ master_server_ip | default('i.p.server.master') }}"
          - "Directorio remoto: /home/admin/wwwroot/dolibarr_documents/sellyoursaas"
          - "Punto de montaje: /home/admin/wwwroot/dolibarr_documents/sellyoursaas"
          - "Tipo de montaje: NFSv4 (por defecto)"
          - "Comandos ejecutados:"
          - "  • apt install nfs-common"
          - "  • mount -t nfs {{ master_server_ip | default('i.p.server.master') }}:/home/admin/wwwroot/dolibarr_documents/sellyoursaas /home/admin/wwwroot/dolibarr_documents/sellyoursaas"
          - "  • umount /home/admin/wwwroot/dolibarr_documents/sellyoursaas"
          - "  • echo '{{ master_server_ip | default('i.p.server.master') }}:/home/admin/wwwroot/dolibarr_documents/sellyoursaas /home/admin/wwwroot/dolibarr_documents/sellyoursaas  nfs  defaults 0 0' >> /etc/fstab"
          - "  • mount -a"
          - "Verificaciones:"
          - "  • Montaje activo: {{ 'OK' if nfs_active_mount.rc == 0 else 'ERROR' }}"
          - "  • Conectividad: {{ 'OK' if nfs_connectivity.rc == 0 else 'Verificar firewall' }}"
          - "  • Acceso de lectura: {{ 'OK' if nfs_read_test.rc == 0 else 'ERROR' }}"
          - "  • Servicio nfs-common: {{ 'OK' if nfs_client_status.rc == 0 else 'ERROR' }}"
          - "Nota: Asegúrate de que el firewall esté abierto entre cliente y servidor NFS"
